# Generated by Django 6.1.1 on 2026-09-27 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacity_requests', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Application matching score 0-100, not scientific certainty.')),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='capacity_requests.capacityrequest')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='resources.resource')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('request', 'resource'), name='unique_request_resource_match')],
            },
        ),
    ]
