# Generated by Django 6.1.1 on 2026-09-27 21:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transportation', 'Transportation'), ('storage', 'Storage'), ('space', 'Spaces & Venues'), ('equipment', 'Equipment')], max_length=20)),
                ('resource_type', models.CharField(blank=True, help_text="Specific kind of resource, e.g. 'hall', 'classroom'.", max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('capacity_required', models.PositiveIntegerField(help_text='How much capacity is needed (people, boxes, items...).', validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('requirements', models.TextField(blank=True, help_text="Extra constraints, e.g. 'must have projector'.")),
                ('status', models.CharField(choices=[('active', 'Active'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=12)),
                ('original_text', models.TextField(blank=True, help_text='The natural-language request as the user said it.')),
                ('structured_data', models.JSONField(blank=True, help_text='Validated parser output (Stage 4B); never trusted blindly.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='request_start_before_end')],
            },
        ),
    ]
